CREATE TABLE FREQUENCIA(
    ALUNO CHAR(14) NOT NULL,
    TURMA NUMBER() NOT NULL,
    DATA_AULA DATE NOT NULL,

    CONSTRAINT FK_FREQUENCIA_ALUNO FOREIGN KEY (ALUNO) REFERENCES ALUNO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_FREQUENCIA_AULA FOREIGN KEY (TURMA, DATA_AULA) REFERENCES AULA(TURMA, DATA) ON DELETE CASCADE,
    CONSTRAINT PK_FREQUENCIA PRIMARY KEY(ALUNO, TURMA, DATA_AULA)
);

CREATE TABLE EXERCICIO(
    TURMA NUMBER() NOT NULL,
    DATA_AULA DATE NOT NULL,
    NUMERO NUMBER(2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    GABARITO CHAR(1) NOT NULL,
    DATA_ENTREGA DATE NOT NULL,

    CONSTRAINT CK_EXERCICIO CHECK(UPPER(GABARITO) IN ('A', 'B', 'C', 'D', 'E')),
    CONSTRAINT FK_EXERCICIO_AULA FOREIGN KEY (TURMA, DATA_AULA) REFERENCES AULA(TURMA, DATA) ON DELETE CASCADE,
    CONSTRAINT PK_EXERCICIO PRIMARY KEY(TURMA, DATA_AULA, NUMERO)
);

CREATE TABLE RESPOSTA(
    ALUNO CHAR(14) NOT NULL,
    TURMA VARCHAR2() NOT NULL,
    DATA_AULA DATE NOT NULL,
    EXERCICIO NUMBER() NOT NULL,
    ALTERNATIVA CHAR(1) NOT NULL,
    DATA_SUBMISSAO DATE NOT NULL,
    COMENTARIO VARCHAR2(),

    CONSTRAINT CK_RESPOSTA CHECK(UPPER(ALTERNATIVA) IN ('A', 'B', 'C', 'D', 'E')),
    CONSTRAINT FK_RESPOSTA_EXERCICIO FOREIGN KEY (TURMA, DATA_AULA, EXERCICIO) REFERENCES EXERCICIO(TURMA, DATA_AULA, NUMERO) ON DELETE CASCADE,
    CONSTRAINT FK_RESPOSTA_ALUNO FOREIGN KEY (ALUNO) REFERENCES ALUNO(CPF) ON DELETE CASCADE,
    CONSTRAINT PK_RESPOSTA PRIMARY KEY (ALUNO, TURMA, DATA_AULA, EXERCICIO)
);

CREATE TABLE MONITORIA(
    TURMA NUMBER() NOT NULL,
    MONITOR CHAR(14) NOT NULL,

    CONSTRAINT FK_MONITORIA_TURMA FOREIGN KEY (TURMA) REFERENCES TURMA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MONITORIA_MONITOR FOREIGN KEY (MONITOR) REFERENCES MONITOR(CPF) ON DELETE CASCADE,
    CONSTRAINT PK_MONITORIA PRIMARY KEY (TURMA, MONITOR)
);