-- Liste o nome, ano escolar de todos os alunos que cursaram todos os cursos dados pelo coordenador 'Ana Oliveira'
SELECT A.nome, A.ano_escolar, A.grau_ensino FROM ALUNO A
WHERE NOT EXISTS (
	(SELECT C.LINGUAGEM, C.ANO, C.SEMESTRE FROM CURSO C 
    JOIN COORDENADOR CO ON C.COORDENADOR =  CO.CPF 
    WHERE CO.NOME = 'ANA OLIVEIRA')
	MINUS
	(SELECT CS.LINGUAGEM, CS.ANO, CS.SEMESTRE FROM ALUNO_PERT_TURMA APT 
    JOIN TURMA T ON APT.ID = T.ID AND APT.ALUNO = A.CPF
    JOIN CURSO CS ON CS.LINGUAGEM = T.LINGUAGEM AND CS.ANO = T.ANO AND CS.SEMESTRE = T.SEMESTRE)
);


-- Liste em ordem decrescente a razão de manutenções por número de empréstimos dos modelos de dispositivos agrupados por modelo com pelo menos 1 manutenção.
SELECT MODELO, ROUND((SUM(QTD_MANUTENCAO) / SUM(N_EMPRESTIMOS)), 2) AS MANUTENCAO_POR_EMPRESTIMO
FROM (
    SELECT D.NUMERO_SERIAL, D.TIPO, D.MODELO, D.QTD_MANUTENCAO, COUNT(E.DATA) AS N_EMPRESTIMOS 
    FROM DISPOSITIVO D
    JOIN EMPRESTIMO E ON E.DISPOSITIVO = D.NUMERO_SERIAL
    GROUP BY D.NUMERO_SERIAL, D.TIPO, D.MODELO, D.QTD_MANUTENCAO
)
GROUP BY MODELO
HAVING SUM(QTD_MANUTENCAO) > 0
ORDER BY MANUTENCAO_POR_EMPRESTIMO DESC;


-- Qual a porcentagem de acertos dos exercícios por oferecimento do curso de ‘Python’ e ‘Javascript’.
SELECT T.LINGUAGEM, T.ANO, T.SEMESTRE,T.NUMERO_TURMA,
    COUNT(CASE WHEN E.GABARITO = R.ALTERNATIVA THEN 1 END) * 100 / COUNT(*) || '%' as "PORCENTAGEM DE ACERTOS"
FROM TURMA T
JOIN EXERCICIO E ON T.ID = E.TURMA
JOIN RESPOSTA R ON R.TURMA = E.TURMA AND R.DATA_AULA = E.DATA_AULA AND R.EXERCICIO = E.NUMERO
WHERE T.linguagem = 'PYTHON' OR T.linguagem = 'JAVASCRIPT'
GROUP BY T.LINGUAGEM, T.ANO, T.SEMESTRE, T.NUMERO_TURMA;



-- Liste todos os monitores e para aqueles que deram monitoria em 2021 especifique a porcentagem de alunos que realizaram empréstimos neste ano.
SELECT M.NOME, M.CPF, J.PORCENTAGEM_EMPRESTIMO AS "PORCENTAGEM DE EMPRESTIMOS EM 2021 (%)"
FROM MONITOR M
LEFT JOIN (
    SELECT MTRA.MONITOR, T.ANO, 
        100 * ROUND(COUNT(CASE WHEN EXTRACT(YEAR FROM E.DATA) = 2021 THEN 1 ELSE NULL END) / COUNT(*), 4) AS PORCENTAGEM_EMPRESTIMO
    FROM MONITORIA MTRA
    JOIN TURMA T ON MTRA.TURMA = T.ID AND T.ANO = 2021
    JOIN ALUNO_PERT_TURMA APT ON T.ID = APT.ID
    LEFT JOIN EMPRESTIMO E ON APT.ALUNO = E.ALUNO
    GROUP BY MTRA.MONITOR, T.ANO
) J 
ON M.CPF = J.MONITOR
ORDER BY M.NOME;


-- Liste todas as escolas que não possuem aluno com dispositivos emprestados da empresa ‘Comércio e Simões EFG’.
SELECT ESC.NOME, ESC.CODIGO_INEP 
FROM ESCOLA_PARCEIRA ESC
WHERE NOT EXISTS(
    SELECT A.ESCOLA FROM ALUNO A 
    JOIN EMPRESTIMO E ON E.ALUNO = A.CPF
    JOIN DISPOSITIVO D ON D.NUMERO_SERIAL = E.DISPOSITIVO
    JOIN EMPRESA EMP ON D.EMPRESA = EMP.CNPJ
    WHERE D.STATUS = 'EMPRESTADO' AND EMP.NOME = 'COMÉRCIO E SIMÕES EFG' AND ESC.CODIGO_INEP = A.ESCOLA
);