-- Liste o nome, ano escolar de todos os alunos que cursaram todos os cursos dados pelo coordenador ‘Jony’
SELECT A.nome, A.ano_escolar, A.grau_ensino FROM ALUNO A
	WHERE NOT EXISTS (
	SELECT C.LINGUAGEM, C.ANO, C.SEMESTRE FROM CURSO C JOIN COORDENADOR CO ON C.COORDENADOR =  CO.CPF WHERE CO.NOME = 'ANA OLIVEIRA'
	MINUS
	SELECT CS.LINGUAGEM, CS.ANO, CS.SEMESTRE FROM ALUNO_PERT_TURMA APT JOIN TURMA T ON APT.ID = T.ID AND APT.ALUNO = A.CPF
    JOIN CURSO CS ON CS.LINGUAGEM = T.LINGUAGEM AND CS.ANO = T.ANO AND CS.SEMESTRE = T.SEMESTRE
);



-- Liste em ordem decrescente a razão de manutenções por número de empréstimos dos modelos de dispositivos agrupados por tipo.
SELECT D.TIPO AS TIPO_DISPOSITIVO, D.MODELO AS MODELO_DISPOSITIVO, 
COUNT(M.DISPOSITIVO) / COUNT(E.DISPOSITIVO) AS RAZAO_MANUT_EMPRESTIMO
FROM DISPOSITIVO D
LEFT JOIN MANUTENCAO M ON D.NUMERO_SERIAL = M.DISPOSITIVO
LEFT JOIN EMPRESTIMO E ON E.NUMERO_SERIAL = E.DISPOSITIVO
GROUP BY D.TIPO, D.MODELO
ORDER BY RAZAO_MANUT_EMPRESTIMO DESC;


-- Qual a porcentagem de acertos dos exercícios por oferecimento do curso de ‘Python’ e ‘Javascript’.
SELECT C.LINGUAGEM, C.ANO, C.SEMESTRE,r.ALTERNATIVA, e.GABARITO
    -- COUNT(CASE WHEN E.GABARITO = R.ALTERNATIVA THEN 1 END) * 100 / COUNT(*) as TOTAL
    FROM CURSO C
    JOIN TURMA T ON C.LINGUAGEM = T.LINGUAGEM AND C.ANO = T.ANO AND C.SEMESTRE = T.SEMESTRE
    JOIN EXERCICIO E ON T.ID = E.TURMA
    JOIN RESPOSTA R ON R.TURMA = E.TURMA AND R.DATA_AULA = E.DATA_AULA AND R.EXERCICIO = E.NUMERO
		    WHERE C.linguagem = 'PYTHON' OR C.linguagem = 'JAVASCRIPT';
    -- GROUP BY C.LINGUAGEM, C.ANO, C.SEMESTRE
--...



-- Liste todos os monitores e para aqueles que deram monitoria em 2021 especifique a porcentagem de alunos que realizaram empréstimos neste ano.
SELECT M.NOME, M.CPF, JUNC.PORCENTAGEM_EMPRESTIMO AS "PORCENTAGEM DE EMPRESTIMOS EM 2021"
    FROM MONITOR M
	LEFT JOIN (
        SELECT MTRA.MONITOR, ROUND(COUNT(E.ALUNO) / COUNT(*), 2) AS PORCENTAGEM_EMPRESTIMO
        FROM MONITORIA MTRA
        JOIN TURMA T
        ON MTRA.TURMA = T.ID
        JOIN ALUNO_PERT_TURMA APT
        ON T.ID = APT.ID
        LEFT JOIN EMPRESTIMO E
        ON APT.ALUNO = E.ALUNO
        WHERE T.ANO = 2021
        GROUP BY MTRA.MONITOR
    ) JUNC
    ON M.CPF = JUNC.MONITOR;

-- Liste todas as escolas que não possuem aluno com dispositivos emprestados da empresa ‘Comércio e Simões EFG’.
